# Copyright 2022 Manna Harbour
# https://github.com/manna-harbour/miryoku

name: 'corne nice_nano 2 with mouse'
on: workflow_dispatch
jobs:
  build:
    uses: ./.github/workflows/main.yml
    secrets: inherit
    with:
      custom_config: '["#define MIRYOKU_KLUDGE_MOUSEKEYSPR\n#define MIRYOKU_ALPHAS_QWERTY"]'
      board: '["nice_nano_v2"]'
      shield: '["corne_left","corne_right"]'
      branches: '["zmkfirmware/zmk/main caksoylar/zmk/feat/mouse-keys-3.2"]'
